/** Human labels for activity_events actions, shared by the timeline and its filter. */
export const ACTION_LABELS: Record<string, string> = {
  "topic.submit": "submitted a topic",
  "topic.publish": "published a topic",
  "topic.reject": "rejected a topic",
  "topic.unpublish": "unpublished a topic",
  "topic.request_changes": "requested changes",
  "topic.edit": "edited a topic",
  "topic.reassign": "reassigned a topic's owner",
  "hearts.archive": "archived hearts on a topic",
  "hearts.cutoff": "changed the hearts cutoff",
  "comment.hide": "hid a comment",
  "member.bio_edit": "edited a member bio",
  "heart.add": "hearted a topic",
  "heart.remove": "removed their heart from a topic",
  "comment.add": "commented on a topic",
  "comment.reply": "replied to a comment",
  "member.invite": "invited someone",
  "member.first_login": "logged in for the first time",
};
